# Copyright 2024 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Set up Buildozer
description: Installs Buildozer build tool for Bazel into path
inputs:
  version:
    description: Release version
    required: true
  sha256:
    description: SHA-256 digest of executable
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      env:
        VERSION: ${{ inputs.version }}
        SHA256: ${{ inputs.sha256 }}
      run: |
        mkdir -p ~/.local/bin
        cd ~/.local/bin
        
        curl -L -o buildozer "https://github.com/bazelbuild/buildtools/releases/download/v${VERSION}/buildozer-linux-amd64"
        echo "${SHA256}  buildozer" | sha256sum --check
        chmod +x buildozer
