# Copyright 2021 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Bazel build and test
description: Build and test all targets using Bazelisk.
inputs:
  workspace-path:
    description: Path of Bazel workspace
    required: true
    default: .
  cache-version:
    description: Version of the GitHub Actions cache key.
    required: false
    default: 0
  cache-save-events:
    # TODO(actions/toolkit#184): Use list type rather than newline-delimited
    # string once it's available.
    description: >-
      Workflow trigger event names which the Bazel workspace cache is saved.
      Newline-delimited.
    required: false
    default: push
  build-options:
    # TODO(actions/toolkit#184): Use list type rather than newline-delimited
    # string once it's available.
    description: >-
      Options to pass to the Bazel build and test commands. Newline-delimited.
    required: false
    default: ''
  restore-cache:
    description: >-
      Whether to restore any previously saved Bazel workspace cache. Boolean.
    required: false
    default: true
  target-patterns:
    description: Bazel targets to build and test. Newline-delimited.
    required: false
    default: '//...'
runs:
  using: node16
  main: index.js
  post: upload-testlogs.js
  post-if: failure()
